### PR TITLE
Add Random Token Simulator

### PR DESCRIPTION
**Pull request by 108anup**

### CODE REVIEW

**Comment by swapagarwal** [comment]
*january *bias and squash, you know the drill! :smirk:

**Comment by 108anup** [comment]
done

**Comment by 108anup** [comment]
i have a problem installing heroku:
SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)

**Comment by swapagarwal** [comment]
*simulate :unamused: 
Let's take that heroku one over gitter.

**Comment by 108anup** [comment]
finally i think

**Comment by swapagarwal** [comment]
:+1:

**Comment by 108anup** [comment]
pls come on gitter

**Pull request merged**
